
<?php
	
	$menuPages =  $this->container->getPages();
	$outter = 0;
	$inner = 0;
	
	foreach ($menuPages as $page) {
		$liClass = array();
			
		$cls = $page->getClass();
		
		if ($page->isActive(false)) {
			$liClass[] = 'active';
		}
		
		if (!$page->getHref()) {
			$liClass[] = 'nav-header';
		}
		
		if ($page->getLabel() !== null && $page->isVisible(true)) {
			echo '<li class="' . join(' ', $liClass) . '">';
			echo ($cls?"<i class='icon-$cls'></i>&nbsp;":"");
			echo $this->menu()->htmlify($page);
			echo '</li>', PHP_EOL;
		}
		
	}
	
	
	
	/*
	<li class=""><a href="/en/about.html">About</a></li>
	<li class="user dropdown" id="menu-ef9a9bc02e19b293778eaaf6748bf4fa">
	<a class="dropdown-toggle" data-toggle="dropdown" href="#menu-ef9a9bc02e19b293778eaaf6748bf4fa">Tests&nbsp;<b class="caret"></b></a><ul class="dropdown-menu">
	<li><a href="/en/tests">Elements</a></li>
	<li><a href="/en/tests/index/controls">Controls</a></li>
	<li><a href="/en/tests/index/markup">Markup</a></li>
	<li><a class="ajax" href="/en/tests/index/ajax">Ajax Messages</a></li>
	</ul>
	</li>
	<li class=""><a href="/en/blog">Blog</a></li>
	<li class=""><a href="/en/forum">Forum</a></li>
	<li class=""><a href="/en/faq">Faq</a></li>
	<li class=""><a title="sitemap" href="/en/sitemap.html">Sitemap</a></li>
	<li class=""><a href="/en/users/register">Registration</a></li>
	<li class=""><a href="/en/login">Login</a></li>
	*/


	/* foreach ($this->container as $pages) {		
		
		// loop next level
		foreach ($pages as $page) {
			//@var Zend_Navigation_Page $page
			// check if it is active (not recursive)
			$liClass = array();
			
			$cls = $page->getClass();
			
			if ($page->isActive(false)) {
				$liClass[] = 'active';
			}
			
			if (!$page->getHref()) {
				$liClass[] = 'nav-header';
			}
			
			echo 'page label: ' .$page->getLabel() .'<br />';
			
			if ($page->getLabel() !== null && $page->isVisible(true)) {
				echo '<li class="' . join(' ', $liClass) . '">';
				echo ($cls?"<i class='icon-$cls'></i>&nbsp;":"");
				echo $this->menu()->htmlify($page);
				echo '</li>', PHP_EOL;
			}
			
			// check if it is active (recursive)
			$isActivePart = $page->isActive(true);
			
			if ($subPages = $page->getPages()) {
				foreach ($subPages as $subPage) {
					if ($subPage->isActive()) {
						$liClass = 'active';
					} elseif (!$isActivePart) {
						$liClass = 'hide';
					} else {
						$liClass = '';
					}
					//$liClass = $page->isActive() ? 'active' : '';
					if ($subPage->getLabel() !== null && $subPage->isVisible(true)) {
						echo '<li class="' . $liClass . '">' . $this->menu()->htmlify($subPage);
						echo '</li>', PHP_EOL;
					}
				}
			}		
		}
	} */
?>