<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <h1><a class="brand" href="/"><?php echo $this->translate('home_header_title');?></a></h1>
            <div class="nav-collapse pull-right">
                <ul class="nav">
                <?php
				
					$nav = $this->navigation();
					
					echo $this->navigation()
							->menu()
							->setPartial('/partial/dashboardMenu.phtml')
							->setMaxDepth(10)
							->setMinDepth(0);
				?>
				</ul>
            </div>
            <div id="loading" class="pull-right"></div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<!-- 

<div id="header">
	<div id="header-logo">
		<h1><?php echo $this->translate('home_body_h2_header');?></h1>
		<div>
			<?php echo $this->navigation()->menu();?>
		</div>
		<div id="breadcrumbs">
		
		<?php 
			
			$breadcrumbs = $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(" : ");
			
		?>
		
		</div>		
	</div>
	<div style="float:right;">
	<?php if ($locale != "sr"){ ?>
	<a href="<?php echo $this->url(array('lang' => 'sr', 'module' => 'default', 'controller' => $currentController, 'action' => 'index'), 'defaultModuleRoute'); ?>">Serbian</a>
	<?php } ?>
	<?php if ($locale != "en"){ ?>
	<a href="<?php echo $this->url( array('lang' => 'en', 'module' => 'default', 'controller' => $currentController, 'action' => 'index'), 'defaultModuleRoute'); ?>">English</a>
	<?php }?>
	</div>
</div>

-->


	
