<?php


$front = Zend_Controller_Front::getInstance();
$router = Zend_Controller_Front::getInstance()->getRouter();
$currentRoute = $router->getCurrentRouteName();
$currentRoute = ($currentRoute == "lang")? "default": $currentRoute;


//Zend_Registry::getInstance()->Zend_Locale->setLocale($locale);
$translate = Zend_Registry::getInstance()->Zend_Translate;
$translate->getAdapter()->setLocale(Zend_Registry::getInstance()->Zend_Locale);
Zend_Controller_Router_Route::setDefaultTranslator($translate);

$currentController = $front->getRequest()->getControllerName();
$currentAction = $front->getRequest()->getActionName();
$locale = $this->translate()->getLocale();


echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName(). '<br />';
echo Zend_Controller_Front::getInstance()->getRequest()->getActionName(). '<br />';
echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName(). '<br />';
//echo var_dump($this->translate()) . '<br />';

?>

<div style="float:right;">
	<?php if ($locale != "sr"){ ?>
	<a href="<?php echo $this->url(array("lang" => "sr", 'controller' => $currentController, 'action'=>$currentAction), $currentRoute); ?>">Serbian</a>
	<?php } ?>
	<?php if ($locale != "en"){ ?>
	<a href="<?php echo $this->url(array("lang" => "en"), $currentRoute); ?>">English</a>
	<?php } ?>
</div>
<?php
//Zend_Debug::dump($this->url());	
//echo $this->headLink()->appendStylesheet($this->baseUrl("/css/about.css"));
?>
<h1>You are in the admin section (I should be red!)</h1>
<h2><?php echo $this->translate('contact_body_h2_header'); ?></h2>