<?php 

echo $this->headLink()->appendStylesheet($this->baseUrl("/css/users.css"));

?>

<a href="<?php echo $this->url(
			array(
				'module' 	 => 'default',
				'controller' => 'user',
				'action'     => 'sign'
			),
			'localized',
			true) ?>">Add New Client
</a>

<div class="clear">&nbsp;</div>

<table id="datatable" class="display">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Phone</th>
		</tr>
	</thead>
	<tbody>
		<?php 
			//foreach ($this->paginator as $entry):
			foreach ($this->rows as $row):
			
		?>
		<tr>			
			<th><?php echo $row->name?></th>
			<th><?php echo $row->email?></th>
			<th><?php echo $row->phone?></th>		
		</tr>
		<?php endforeach;?>
	</tbody>
</table>
<div>
<?php //echo $this->paginationControl($this->paginator, 'Jumping', '/controls/controls.phtml');?>
</div>