<?php echo $this->headLink()->appendStylesheet($this->baseUrl("/css/about.css")); ?>
<div style="clear: both; float: left;">
	<h2>The Web is not a game. Make it work for you.</h2>
	<ul id="double">
		<li><strong>Web applications should transform your business.</strong><br />
			We're not just interested in making your current system better. We're
			interested in developing software that takes your entire organization
			to the next level. Custom software should provide truly transformative
			solutions.</li>
	
		<li><strong>Wherever you are is the perfect place to start.</strong><br />
			Bring us your big ideas&mdash;no matter where you are in the creative
			process. We'll collaborate to refine your idea&mdash;and create an end
			product that delivers exceptional results.</li>
	
		<li><strong>Business understanding should drive
				development.</strong><br /> We don't write a line of code until we
			know your business as well as you do. And our process encourages your
			participation and feedback every step of the way&mdash;so you can be
			sure of the final product.</li>
	
		<li><strong>Great software is not about the programming.</strong><br />
			It's about business needs and usability and market understanding and
			strategy and your bottom line. Most development houses don't take all
			those things into account. We do.</li>
	
		<li><strong>Innovation is NOT black magic.</strong><br />Innovation
			is a natural result of a development process that draws feedback from
			users at every level of your company. We listen actively&mdash;and we
			don't build until we all share a complete picture of your
			organization's needs and goals.</li>
	
		<li><strong>Your final product should be flawless.</strong><br /> It's
			why we build you a prototype you can test drive&mdash;long before we
			build the software. It's why we pull in focus groups of your core
			users to test it. And it's why we test exhaustively in-house to make
			our software perfect&mdash;before the launch.</li>
	</ul>
</div>