<?php 
//Zend_Debug::dump($this->navigation()->getTranslator());
//Zend_Debug::dump($this->translate()->getLocale());
//Zend_Debug::dump($this->url());
//echo 'this url: ' . $this->url(array('lang' => 'sr')) . '<br />';
//echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName(). '<br />';
//echo Zend_Controller_Front::getInstance()->getRequest()->getActionName(). '<br />';
//echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName(). '<br />';


$front = Zend_Controller_Front::getInstance();
$router = Zend_Controller_Front::getInstance()->getRouter();
$currentRoute = $router->getCurrentRouteName();
$currentRoute = ($currentRoute == "lang") ? "default": $currentRoute;

$currentController = $front->getRequest()->getControllerName();


$translate = Zend_Registry::get('Zend_Translate');

var_dump($translate);

$currentAction = $front->getRequest()->getActionName();
$locale = $this->translate()->getLocale();

// Output list of routes, in the order they are matched
echo '<ol>';
$routes = array_reverse($router->getRoutes());
foreach ($routes as $name => $route) {
	echo "	<li>$name</li>\n";
}
echo '</ol>';

$current = (string)$currentController;
$prevod = $translate->translate($current);
echo "prevod $prevod na $current<br />";

//var_dump($this->translate());

?>
<div id="header">
	<div id="header-logo">
		<h1><?php echo $this->translate('home_header_title');?></h1>
		<div>
			<?php echo $this->navigation()->menu();?>
		</div>
		<div id="breadcrumbs">
		
		<?php 
			
			$breadcrumbs = $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(" : ");
			//echo $breadcrumbs;
		?>
		
		</div>		
	</div>
	<div style="float:right;">
	<?php if ($locale != "sr"){ ?>
	<a href="<?php echo $this->url(array("lang" => "sr", 'controller' => $prevod, 'action'=>$currentAction), $currentRoute); ?>">Serbian</a>
	<?php } ?>
	<?php if ($locale != "en"){ ?>
	<a href="<?php echo $this->url(array("lang" => "en", 'controller' => $prevod, 'action'=>$currentAction), $currentRoute); ?>">English</a>
	<?php }?>
	</div>
</div>

